# -*- coding: utf-8 -*-
"""Auto_repeticao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8KhtQaDsIQPUiRpWq0KaqnbP_ZN_HJp
"""

from turtle import *
speed(5)
shape("turtle")


for count in range(50):
    color('red')
    pinsize(5)
    forward(5)
    penup()
    forward(5)
    pendown()


done()