# -*- coding: utf-8 -*-
"""Desenhando_Padroes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nnu1w2RUEbanLd1ng_zWchVCBE5Y3qob
"""

from turtle import *

speed(11)
shape("turtle")
pensize(6)
color("red")

for count in range(36):
    forward(100)
    right(100)

done()