# -*- coding: utf-8 -*-
"""ola_turtler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Liqf115CQ9dPcGjGw7s1eaZdMwj_AjbH
"""

from turtle import *
shape("turtle")
speed(8)


color('black')
pensize(7)
right(90)
forward(100)
left(90)
forward(50)

color('Red')
pensize(3)
penup()
forward(50)
pendown()
forward(50)

done()