# -*- coding: utf-8 -*-
"""Variaveis_Loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19CeCBskfZkL1jB4t_vIlh1r-E3QwLQH4
"""

lados = 16
angulo = 360 / lados
print(angulo)